before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y openjdk-8-jre
  - sudo apt-get install -y openjdk-8-jre-headless

install:
  - bundle install --path vendor/bundle

script:
  - bundle exec rspec spec
